package grack.dev.moviedagger.network.interceptor

object ResponseCode {

  const val RESPONSE_SUCCESS = 200
  const val RESPONSE_BAD_REQUEST = 400
  const val RESPONSE_UNAUTHORIZED = 401
  const val RESPONSE_FORBIDDEN = 403
  const val RESPONSE_NOT_FOUND = 404
  const val RESPONSE_REQUEST_TIMEOUT = 408
  const val RESPONSE_INTERNAL_SERVER_ERROR = 500
  const val RESPONSE_BAD_GATEWAY = 502
  const val RESPONSE_SERVICE_UNAVAILABLE = 503
  const val RESPONSE_GATEWAY_TIMEOUT = 504

  const val SUCCESS = "SUCCESS"
  const val BAD_REQUEST = "BAD_REQUEST"
  const val UNAUTHORIZED = "UNAUTHORIZED"
  const val FORBIDDEN = "FORBIDDEN"
  const val NOT_FOUND = "NOT_FOUND"
  const val REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
  const val INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
  const val BAD_GATEWAY = "BAD_GATEWAY"
  const val SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
  const val GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT"
}